### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by xenoner1506** [Kharichkin/2sem_informatics_CPP#1]
Some notes about 1week exercises:

1.  If you write `{` in line with a loop statement, then you must make it for all functions (for main() too).
2.  `exercise2/exercise2/exercise2.cpp` is not compiled by pure `g++` compiler. You must include `<cmath>` library.
3.  It doesn't matter, but try to use `for (int i = 0; i < N; i++)` (notice that you are programmer ^_^)

**Comment by appleivanko** [comment]
Corrected in "lab1 CLIon" commit
